import char0 from 'char0.png';
import char1 from 'char1.png';
import char2 from 'char2.png';
import char3 from 'char3.png';
import char4 from 'char4.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';
// export * from 'char1.png';

export default { char0, char1, char2, char3, char4 };
